### ISSUE TITLE
Login does not work if you have a "/" at the end of the URL

### ISSUE THREAD

**Issue by greenscientist** [chairemobilite/transition_qgis#13]
If you do http://localhost:8080 it works, and http://localhost:8080/ it does not

**Comment by greenscientist** [comment]
@tahini , do you think we should do the cleanup in QGIS, or filter it out in the python lib ?

**Comment by tahini** [comment]
I think fixing it in the python lib would be the best approach, as this "issue" will be found there eventually too

**Comment by greenscientist** [comment]
Yes, after reflexion, that's what I'm doing.
