### ISSUE TITLE
Error when activating plugin after install

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition_qgis#24]
Plugin installs correctly, but when activating the plugin, the following error message is displayed:

`ModuleNotFoundError: No module named 'geojson'`

QGIS version 3.32.2-Lima
Python version 3.9.5

**Comment by tibobliss** [comment]
Closing QGIS when the plugin has been activated (checkmark active) but after error message results in QGIS being unable to open again - stuck on splash screen at step `Reconstitution des extensions chargées`.

**Comment by davidmurray** [comment]
@tibobliss I had the same issue regarding the missing the `geojson` package. See my issue here https://github.com/chairemobilite/transition_qgis/issues/22

**Comment by tibobliss** [comment]
Ça marche! Mais c'est pas super convivial...

**Comment by tahini** [comment]
> Ça marche! Mais c'est pas super convivial...

ça fonctionne avec le workaround de David?
